// nodes/web/resources/scripts/components/ServoControl.jsx
import React, { useState, useEffect } from 'react';
import node from '../Node';
import { useAppContext } from '../contexts/AppContext';
import Slider from 'rc-slider';

const ServoControl = ({ servoId }) => {
  const { availableServos } = useAppContext();
  const [showSettings, setShowSettings] = useState(false);
  const [position, setPosition] = useState(0);
  const [speed, setSpeed] = useState(100);
  const [min, setMin] = useState(0);
  const [max, setMax] = useState(180);
  const [servoInfo, setServoInfo] = useState(null);
  
  // Find the servo data from available servos
  useEffect(() => {
    console.log('[SERVO-DEBUG] ServoControl useEffect for servoId:', servoId);
    console.log('[SERVO-DEBUG] Available servos:', availableServos);
    
    if (availableServos && availableServos.length > 0) {
      // Ensure we're comparing the same types
      const targetId = parseInt(servoId);
      
      // Log all servo IDs for debugging
      const allIds = availableServos.map(s => typeof s.id === 'string' ? parseInt(s.id) : s.id);
      console.log('[SERVO-DEBUG] Available servo IDs:', allIds);
      console.log('[SERVO-DEBUG] Looking for ID:', targetId);
      
      // Flexible matching with type conversion
      const servo = availableServos.find(s => {
        const currentId = typeof s.id === 'string' ? parseInt(s.id) : s.id;
        const matches = currentId === targetId;
        console.log(`[SERVO-DEBUG] Comparing ${currentId} with ${targetId}: ${matches}`);
        return matches;
      });
      
      if (servo) {
        console.log('[SERVO-DEBUG] Found servo:', servo);
        setServoInfo(servo);
        setPosition(servo.position || 0);
        setSpeed(servo.speed || 100);
        setMin(servo.min_pos || 0);
        setMax(servo.max_pos || 180);
      } else {
        console.warn(`[SERVO-DEBUG] No servo found with ID ${targetId} in:`, allIds);
      }
    }
  }, [availableServos, servoId]);
  
  // Listen for servo updates from WebSocket
  useEffect(() => {
    console.log('[SERVO-DEBUG] Setting up servo_status listener for servoId:', servoId);
    
    const unsubscribe = node.on('servo_status', (event) => {
      console.log('[SERVO-DEBUG] Servo status update received for widget:', servoId);
      
      if (event && event.value) {
        const servos = event.value || [];
        console.log('[SERVO-DEBUG] Received servos in status event:', servos.length);
        
        // Ensure we're comparing the same types
        const targetId = parseInt(servoId);
        
        // Flexible matching with type conversion
        const servo = servos.find(s => {
          const currentId = typeof s.id === 'string' ? parseInt(s.id) : s.id;
          return currentId === targetId;
        });
        
        if (servo) {
          console.log('[SERVO-DEBUG] Found updated servo data:', servo);
          setServoInfo(servo);
          setPosition(servo.position || 0);
          setSpeed(servo.speed || 100);
          setMin(servo.min_pos !== undefined ? servo.min_pos : 0);
          setMax(servo.max_pos !== undefined ? servo.max_pos : 180);
        } else {
          console.warn(`[SERVO-DEBUG] No servo found with ID ${targetId} in status update`);
        }
      }
    });
    
    // Request servo data on mount
    console.log('[SERVO-DEBUG] Requesting SCAN for servo:', servoId);
    node.emit('SCAN', []);
    
    return unsubscribe;
  }, [servoId]);
  
  const handlePositionUpdate = (newPosition) => {
    const positionValue = parseInt(newPosition);
    setPosition(positionValue);
    node.emit('set_servo', [parseInt(servoId), positionValue, parseInt(speed)]);
  };
  
  const handleSpeedChange = (e) => {
    const newSpeed = parseInt(e.target.value);
    setSpeed(newSpeed);
  };
  
  const updateSpeed = () => {
    node.emit('set_speed', [parseInt(servoId), parseInt(speed)]);
  };
  
  const handleWiggle = () => {
    node.emit('wiggle', [parseInt(servoId)]);
  };
  
  const handleCalibrate = () => {
    node.emit('calibrate', [parseInt(servoId)]);
  };
  
  const servoTitle = (() => {
    // Handle undefined servoId
    if (servoId === undefined || servoId === null) {
      return "Servo (unassigned)";
    }
    
    // Handle case with servoInfo and alias
    if (servoInfo && servoInfo.alias) {
      return `${servoInfo.alias} (${servoId})`;
    }
    
    // Default case
    return `Servo ${servoId}`;
  })();
  
  // Fallback slider for small screens
  const FallbackSlider = () => (
    <div className="fallback-slider">
      <input 
        type="range" 
        min={min} 
        max={max} 
        value={position} 
        onChange={(e) => handlePositionUpdate(e.target.value)} 
        className="slider" 
      />
      <div className="slider-value">{position}</div>
    </div>
  );
  
  return (
    <div className="servo-control-widget">
      <div className="widget-header">
        <h6 className="title" style={{ color: 'var(--text)' }}>{servoTitle}</h6>
        <div className="flex-spacer"></div>
        <a className="settings-button" onClick={() => setShowSettings(!showSettings)}>
          <i className="fas fa-cog"></i>
        </a>
      </div>
      
      {!showSettings ? (
        <div className="widget-content">
          <div className="control-area">
            <div className="circular-slider-container">
              <div className="position-display">{position}</div>
              <div className="slider-container">
                <Slider
                  value={position}
                  min={min}
                  max={max}
                  onChange={handlePositionUpdate}
                  railStyle={{ backgroundColor: '#37474F', height: 8 }}
                  trackStyle={{ backgroundColor: '#00bfa5', height: 8 }}
                  handleStyle={{
                    borderColor: '#00bfa5',
                    height: 20,
                    width: 20,
                    marginTop: -6,
                    backgroundColor: '#fff',
                    boxShadow: '0 2px 5px rgba(0, 0, 0, 0.3)'
                  }}
                />
              </div>
            </div>
          </div>
          <div className="status-info">
            <div className="info-item">
              <span className="label">Position:</span>
              <span className="value">{position}</span>
            </div>
            <div className="info-item">
              <span className="label">Speed:</span>
              <span className="value">{speed}</span>
            </div>
          </div>
        </div>
      ) : (
        <div className="widget-content settings-panel">
          <div className="field label border round m-bottom-2">
            <label className="slider">
              <input 
                type="range" 
                min="100" 
                max="2000" 
                step="10" 
                value={speed}
                onChange={handleSpeedChange}
                onMouseUp={updateSpeed}
                onTouchEnd={updateSpeed}
              />
              <span className="small">Speed: {speed}</span>
            </label>
          </div>
          
          <button className="border full-width m-bottom-2" onClick={handleWiggle}>
            <i className="fas fa-arrows-left-right m-right-1"></i>
            Test Movement
          </button>
          
          <button className="border full-width" onClick={handleCalibrate}>
            <i className="fas fa-ruler m-right-1"></i>
            Calibrate Range
          </button>
        </div>
      )}
    </div>
  );
};

export default ServoControl;

// nodes/web/resources/scripts/components/ServoControl.vue
<template>
  <div class="servo-control-widget">
    <div class="widget-header">
      <h6 class="title" style="color: var(--text);">{{ servoTitle }}</h6>
      <div class="flex-spacer"></div>
      <a class="settings-button" @click="showSettings = !showSettings">
        <i class="fas fa-cog"></i>
      </a>
    </div>
    
    <!-- Main control display -->
    <div v-if="!showSettings" class="widget-content">
      <div class="control-area">
        <round-slider
          v-model="currentPosition"
          :min="minPos"
          :max="maxPos"
          radius="80"
          :path-color="'#37474F'"
          :range-color="'#00bfa5'"
          :start-angle="315"
          :end-angle="225"
          @change="handlePositionUpdate"
        />
      </div>
      <div class="status-info">
        <div class="info-item">
          <span class="label">Position:</span>
          <span class="value">{{ currentPosition }}</span>
        </div>
        <div class="info-item">
          <span class="label">Speed:</span>
          <span class="value">{{ currentSpeed }}</span>
        </div>
      </div>
    </div>
    
    <!-- Settings panel -->
    <div v-else class="widget-content settings-panel">
      <div class="field label border round m-bottom-2">
        <label class="slider">
          <input 
            type="range" 
            min="100" 
            max="2000" 
            step="10" 
            v-model="currentSpeed"
            @change="updateSpeed"
          >
          <span class="small">Speed: {{ currentSpeed }}</span>
        </label>
      </div>
      
      <button class="border full-width m-bottom-2" @click="wiggle">
        <i class="fas fa-arrows-left-right m-right-1"></i>
        Test Movement
      </button>
      
      <button class="border full-width" @click="calibrate">
        <i class="fas fa-ruler m-right-1"></i>
        Calibrate Range
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted, defineAsyncComponent } from 'vue';
import node from '../Node.js';

// Attempt to load the round slider component
// If vue-three-round-slider isn't available, we'll create a simple fallback
const RoundSlider = defineAsyncComponent({
  loader: () => import('round-slider').then(() => ({
    props: ['modelValue', 'min', 'max', 'radius', 'lineWidth', 'pathColor', 'rangeColor', 'startAngle', 'endAngle', 'animation'],
    template: `
      <div ref="sliderContainer" class="round-slider-container"></div>
    `,
    mounted() {
      this.initSlider();
    },
    methods: {
      initSlider() {
        const el = this.$refs.sliderContainer;
        if (!el) return;
        
        // Create the slider using round-slider library
        this.slider = $(el).roundSlider({
          radius: this.radius || 85,
          width: this.lineWidth || 16,
          handleSize: '+0',
          sliderType: 'min-range',
          value: this.modelValue,
          min: this.min || 0,
          max: this.max || 1024,
          startAngle: this.startAngle || 315,
          endAngle: this.endAngle || 225,
          rangeColor: this.rangeColor || '#00bfa5',
          pathColor: this.pathColor || '#37474F',
          valueChange: (e) => {
            this.$emit('update:modelValue', e.value);
            this.$emit('change', e.value);
          }
        });
      }
    },
    beforeUnmount() {
      if (this.slider) {
        $(this.$refs.sliderContainer).roundSlider('destroy');
      }
    },
    watch: {
      modelValue(val) {
        if (this.slider && this.slider.getValue() !== val) {
          $(this.$refs.sliderContainer).roundSlider('setValue', val);
        }
      }
    }
  })),
  errorComponent: {
    template: `
      <div class="fallback-slider">
        <input type="range" :min="min" :max="max" :value="modelValue" @input="$emit('update:modelValue', $event.target.value); $emit('change', $event.target.value)" />
        <div class="slider-value">{{ modelValue }}</div>
      </div>
    `,
    props: ['modelValue', 'min', 'max']
  }
});

// Props
const props = defineProps({
  servoId: {
    type: [Number, String],
    required: true
  }
});

// State
const showSettings = ref(false);
const currentPosition = ref(0);
const currentSpeed = ref(100);
const servoData = ref(null);

// Computed
const servoTitle = computed(() => {
  // Check if servoId is defined
  if (props.servoId === undefined || props.servoId === null) {
    console.warn('ServoControl: undefined servoId in props', props);
    return 'Servo (unassigned)';
  }
  
  // Check if servo data is available
  if (!servoData.value) {
    return `Servo ${props.servoId}`;
  }
  
  // Return alias if available
  return servoData.value.alias 
    ? `${servoData.value.alias} (${props.servoId})` 
    : `Servo ${props.servoId}`;
});

const minPos = computed(() => {
  if (!servoData.value || servoData.value.min_pos === undefined) return 0;
  return servoData.value.min_pos;
});

const maxPos = computed(() => {
  if (!servoData.value || servoData.value.max_pos === undefined) return 1024;
  return servoData.value.max_pos;
});

// Methods
function handlePositionUpdate(newValue) {
  if (typeof newValue === 'object' && newValue.value !== undefined) {
    newValue = newValue.value;
  }
  updateServoPosition(parseInt(newValue));
}

function updateServoPosition(position) {
  node.emit('set_servo', [parseInt(props.servoId), position, parseInt(currentSpeed.value)]);
}

function updateSpeed() {
  node.emit('set_speed', [parseInt(props.servoId), parseInt(currentSpeed.value)]);
}

function wiggle() {
  node.emit('wiggle', [parseInt(props.servoId)]);
}

function calibrate() {
  node.emit('calibrate', [parseInt(props.servoId)]);
}

// Event handlers
function updateServoData() {
  const servos = window.availableServos || [];
  
  // Convert id to number for consistent comparison 
  const targetId = parseInt(props.servoId);
  
  console.log(`[SERVO-DEBUG] Looking for servo ID ${targetId} in ${servos.length} available servos`);
  
  if (servos.length > 0) {
    // Log IDs for comparison debug
    const availableIds = servos.map(s => typeof s.id === 'string' ? parseInt(s.id) : s.id);
    console.log(`[SERVO-DEBUG] Available servo IDs: ${JSON.stringify(availableIds)}`);
  }
  
  // Try to find the matching servo
  servoData.value = servos.find(s => {
    const servoId = typeof s.id === 'string' ? parseInt(s.id) : s.id;
    const matches = servoId === targetId;
    console.log(`[SERVO-DEBUG] Comparing ${servoId} (${typeof servoId}) with ${targetId} (${typeof targetId}): ${matches}`);
    return matches;
  }) || null;
  
  if (servoData.value) {
    console.log(`[SERVO-DEBUG] Found servo data for ID ${props.servoId}:`, JSON.stringify(servoData.value));
    currentPosition.value = servoData.value.position || 0;
    currentSpeed.value = servoData.value.speed || 100;
  } else {
    console.warn(`[SERVO-DEBUG] Servo ${props.servoId} not found in available servos`);
  }
}

// Listen for servo status updates
const unsubscribe = node.on('servo_status', (event) => {
  console.log(`[SERVO-DEBUG] Widget for servo ${props.servoId} received servo_status event with ${event.value ? event.value.length : 0} servos`);
  
  // For debugging, log all servos received
  if (event.value && event.value.length > 0) {
    event.value.forEach(servo => {
      console.log(`[SERVO-DEBUG] Available servo: ID=${servo.id}, position=${servo.position}, min=${servo.min_pos}, max=${servo.max_pos}`);
    });
  }
  
  window.availableServos = event.value || [];
  updateServoData();
});

onMounted(() => {
  console.log(`[SERVO-DEBUG] Component mounted for servo ${props.servoId}`);
  updateServoData();
  
  // Request a scan to get fresh servo data
  if (props.servoId !== undefined && props.servoId !== null) {
    console.log(`[SERVO-DEBUG] Requesting servo scan for ${props.servoId}`);
    node.emit('SCAN', []);
  }
});

// Make sure to clean up event listeners when component is unmounted
onUnmounted(() => {
  if (typeof unsubscribe === 'function') {
    unsubscribe();
  }
});
</script>

<style scoped>
.servo-control-widget {
  height: 100%;
  display: flex;
  flex-direction: column;
  background-color: var(--surface);
  color: var(--text);
  border-radius: 8px;
}

.widget-header {
  display: flex;
  align-items: center;
  padding: 10px 16px;
  border-bottom: 1px solid rgba(0,0,0,0.1);
}

.title {
  margin: 0;
  font-size: 16px;
  font-weight: 500;
}

.flex-spacer {
  flex: 1;
}

.settings-button {
  cursor: pointer;
  color: #555;
  padding: 5px;
}

.widget-content {
  flex: 1;
  padding: 16px;
  display: flex;
  flex-direction: column;
}

.control-area {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
}

.status-info {
  margin-top: 16px;
}

.info-item {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
}

.label {
  color: #666;
  font-size: 14px;
}

.value {
  font-weight: 500;
}

.settings-panel {
  padding: 16px;
}

.full-width {
  width: 100%;
}

/* Round slider styling */
.round-slider-container {
  width: 170px;
  height: 170px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.fallback-slider {
  width: 100%;
  text-align: center;
}

.slider-value {
  margin-top: 10px;
  font-weight: bold;
}
</style>
