// nodes/web/resources/scripts/components/Volume.vue
<template>
  <button>
    <span><i class="fa-solid fa-volume-high"></i></span>
    <i>arrow_drop_down</i>
    <menu>
      <article class="small-height round">
        <label class="slider max vertical">
          <input type="range" id="volume" min="0" max="1" value="1" step="0.01" @change="handleVolumeChange">
          <span></span>
        </label>
      </article>
    </menu>
  </button>
</template>
<script setup>
import node from '../Node.js';

function handleVolumeChange(event) {
  node.emit('set_volume', [event.target.value]);
}
</script>

// nodes/web/resources/scripts/components/Volume.jsx
import React, { useState } from 'react';
import node from '../Node';

const Volume = () => {
  const [showVolumeSlider, setShowVolumeSlider] = useState(false);
  const [volume, setVolume] = useState(50);

  const toggleVolumeSlider = () => {
    setShowVolumeSlider(!showVolumeSlider);
  };

  const handleVolumeChange = (e) => {
    const newVolume = parseInt(e.target.value);
    setVolume(newVolume);
    node.emit('set_volume', [newVolume]);
  };

  return (
    <div className="volume-control">
      <button onClick={toggleVolumeSlider} className="transparent circle">
        <i className="fa-solid fa-volume-high"></i>
      </button>
      
      {showVolumeSlider && (
        <div className="volume-slider-container">
          <input 
            type="range" 
            min="0" 
            max="100" 
            value={volume} 
            onChange={handleVolumeChange} 
            className="slider" 
          />
        </div>
      )}
    </div>
  );
};

export default Volume;
