// nodes/web/resources/scripts/views/ServoDebug.vue
<template>
  <div class="servo-debug">
    <article class="responsive">
      <!-- Header Section with Breadcrumb -->
      <header class="m-bottom-2">
        <nav aria-label="breadcrumb">
          <RouterLink to="/" class="small">Home</RouterLink>
          <span class="small">/</span>
          <span class="small" aria-current="page">Servo {{ id }}</span>
        </nav>
        <h5 class="m-top-1">Servo Control Panel</h5>
        <p class="small text-gray">Configure and monitor servo behavior</p>
      </header>

      <div class="grid gap-2">
        <!-- Left Column: Position Control -->
        <div class="s12 m6 l4">
          <section class="card p-2">
            <h6 class="m-bottom-2">Position Control</h6>
            <div class="center-align" role="group" aria-label="Position control">
              <round-slider
                v-model="currentPosition"
                :min="minPos"
                :max="maxPos"
                radius="120"
                line-cap="round"
                path-color="#37474F"
                range-color="#00bfa5"
                :start-angle="300"
                :end-angle="600"
                :animation="false"
                aria-label="Servo position control"
                v-bind:change="handlePositionUpdate"
              />
              <div class="field label border round m-top-2">
                <label class="slider">
                  <input 
                    type="range" 
                    min="100" 
                    max="2000" 
                    step="1" 
                    v-model="newSpeed"
                    aria-label="Servo speed control"
                  >
                  <span class="small">Speed: {{ newSpeed }}</span>
                </label>
              </div>
            </div>
          </section>
        </div>

        <!-- Middle Column: Status and Calibration -->
        <div class="s12 m6 l4">
          <section class="card p-2 m-bottom-2">
            <h6 class="m-bottom-2">Current Status</h6>
            <div class="status-grid">
              <div v-for="(value, key) in servoStatus" :key="key" class="status-item p-1">
                <span class="label text-gray">{{ key }}</span>
                <span class="value">{{ value }}</span>
              </div>
            </div>
          </section>

          <section class="card p-2" v-if="currentServo?.min_pos !== undefined">
            <h6 class="m-bottom-2">Calibration Range</h6>
            <div class="status-grid">
              <div class="status-item p-1">
                <span class="label text-gray">Min Position</span>
                <span class="value">{{ currentServo?.min_pos || 'Not calibrated' }}</span>
              </div>
              <div class="status-item p-1">
                <span class="label text-gray">Max Position</span>
                <span class="value">{{ currentServo?.max_pos || 'Not calibrated' }}</span>
              </div>
            </div>
          </section>
        </div>

        <!-- Right Column: Controls -->
        <div class="s12 m12 l4">
          <section class="card p-2">
            <h6 class="m-bottom-2">Servo Configuration</h6>
            
            <div class="field label round m-bottom-2" style="display: flex;">
              <input 
                class="border"
                type="number" 
                v-model="newId"
                aria-label="New servo ID"
                min="1"
                max="253"
              >
              <label>New Servo ID</label>
              <button 
                @click="changeId"
                :disabled="!newId"
                aria-label="Change servo ID"
              >
                Change ID
              </button>
            </div>

            <div class="field label round m-bottom-2" style="display: flex;">
              <input 
                class="border"
                type="text" 
                v-model="aliasInput"
                aria-label="Servo alias"
                placeholder="Enter alias"
              >
              <label>Servo Alias</label>
              <button 
                @click="setAlias"
                :disabled="!aliasInput"
                aria-label="Set alias"
              >
                Set Alias
              </button>
            </div>

            <div class="actions m-top-2">
              <button 
                class="border m-right-2 p-2"
                @click="wiggle"
                aria-label="Test servo movement"
              >
                <i class="fa-solid fa-arrows-left-right m-right-1"></i>
                Test Movement
              </button>
              <button 
                class="border p-2"
                @click="calibrate"
                aria-label="Calibrate servo range"
              >
                <i class="fa-solid fa-ruler m-right-1"></i>
                Calibrate Range
              </button>
            </div>
          </section>
        </div>
      </div>
    </article>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { useRoute } from 'vue-router';
import node from '../Node.js';
import RoundSlider from 'vue-three-round-slider';

// Route and basic setup
const route = useRoute();
const id = route.params.id;
const servos = ref([]);

// Form controls
const newId = ref('');
const newSpeed = ref(100);
const currentPosition = ref(0);
const aliasInput = ref('');

// Computed properties
const currentServo = computed(() => 
  servos.value.find(servo => servo.id === parseInt(id))
);

const minPos = computed(() => currentServo.value?.min_pos || 0);
const maxPos = computed(() => currentServo.value?.max_pos || 1024);

const servoStatus = computed(() => ({
  Position: currentServo.value?.position || 'N/A',
  Speed: currentServo.value?.speed || 'N/A',
  Torque: currentServo.value?.torque || 'N/A',
  Alias: currentServo.value?.alias || 'None'
}));

// Event handlers
node.on('servo_status', (event) => {
  servos.value = event.value;
  if (currentServo.value?.speed) {
    newSpeed.value = currentServo.value.speed;
  }
  if (currentServo.value?.position) {
    currentPosition.value = currentServo.value.position;
  }
});

// Action methods
function changeId() {
  if (newId.value !== '') {
    node.emit('change_servo_id', [parseInt(id), parseInt(newId.value)]);
  }
}


function wiggle() {
  node.emit('wiggle', [parseInt(id)]);
}

function calibrate() {
  node.emit('calibrate', [parseInt(id)]);
}

function setAlias() {
  if (aliasInput.value.trim()) {
    node.emit('set_alias', [parseInt(id), aliasInput.value.trim()]);
    aliasInput.value = ''; // Clear input after sending
  }
}

watch(newSpeed, (newValue) => {
  if (!currentServo.value) return;
  node.emit('set_speed', [parseInt(id), parseInt(newValue)]);
});

function handlePositionUpdate(newValue) {
  if (typeof newValue === 'object' && newValue.value !== undefined) {
    newValue = newValue.value;
  }
  node.emit('set_servo', [parseInt(id), parseInt(newValue), parseInt(newSpeed.value)]);
}
</script>

<style scoped>
.servo-debug {
  padding: 1rem;
}

.status-grid {
  display: grid;
  gap: 0.5rem;
}

.status-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid var(--border);
}

.status-item:last-child {
  border-bottom: none;
}

.label {
  font-size: 0.875rem;
}

.value {
  font-weight: 500;
}

.actions {
  display: flex;
  gap: 0.5rem;
}

.actions button {
  flex: 1;
  min-height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
}

@media (max-width: 600px) {
  .actions {
    flex-direction: column;
  }
  
  .actions button {
    width: 100%;
    margin-right: 0;
    margin-bottom: 0.5rem;
  }
}
</style>

// nodes/web/resources/scripts/views/ServoDebug.jsx
import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import node from '../Node';
import Slider from 'rc-slider';
import CircularSlider from '@fseehawer/react-circular-slider';

const ServoDebug = () => {
  const { id } = useParams();
  const [servo, setServo] = useState(null);
  const [position, setPosition] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [speed, setSpeed] = useState(100);
  const [min, setMin] = useState(0);
  const [max, setMax] = useState(1024);
  const [newId, setNewId] = useState('');
  const [aliasInput, setAliasInput] = useState('');
  
  useEffect(() => {
    // Listen for servo updates
    const unsubscribe = node.on('servo_status', (event) => {
      const servos = event.value || [];
      const servo = servos.find(s => s.id === parseInt(id));
      if (servo) {
        setServo(servo);
        
        // Get range from servo
        const servoMinPos = servo.min_pos || 0;
        const servoMaxPos = servo.max_pos || 4095;
        setMin(servoMinPos);
        setMax(servoMaxPos);
        
        // Get current servo position
        const servoPosition = servo.position || 0;
        
        // Map servo position (min-max) to UI range (0-180)
        const uiPosition = Math.round(
          180 * (servoPosition - servoMinPos) / (servoMaxPos - servoMinPos)
        );
        
        console.log(`Mapped servo ${servoPosition} to UI position ${uiPosition}°`);
        setPosition(uiPosition);
        setSpeed(servo.speed || 100);
      }
    });
    
    // Request servo status on mount
    node.emit('SCAN', []);
    
    return unsubscribe;
  }, [id]);
  
  const handlePositionChange = (newPosition) => {
    // Ensure we have a valid number
    const positionValue = parseInt(newPosition);
    
    if (!isNaN(positionValue)) {
      console.log("UI position:", positionValue);
      
      // Update the local state immediately for responsive UI
      setPosition(positionValue);
      
      // Map UI slider value (0-180) to servo range (min-max)
      let servoMinPos = min || 0;
      let servoMaxPos = max || 4095;
      
      // Linear mapping from UI range (0-180) to servo range
      const servoPosition = Math.round(
        servoMinPos + (positionValue / 180) * (servoMaxPos - servoMinPos)
      );
      
      console.log(`Mapped ${positionValue}° to servo position ${servoPosition}`);
      
      // Use stronger debounce to limit servo commands
      clearTimeout(window.servoUpdateTimeout);
      window.servoUpdateTimeout = setTimeout(() => {
        // Only send if position hasn't changed in the debounce period
        console.log("Sending to servo:", servoPosition);
        node.emit('set_servo', [parseInt(id), servoPosition]);
      }, 300); // 300ms debounce for smoother experience
    }
  };
  
  const handleSpeedChange = (e) => {
    const newSpeed = parseInt(e.target.value);
    setSpeed(newSpeed);
    node.emit('set_speed', [parseInt(id), newSpeed]);
  };
  
  const handleWiggle = () => {
    node.emit('wiggle', [parseInt(id)]);
  };
  
  const handleCalibrate = () => {
    node.emit('calibrate', [parseInt(id)]);
  };
  
  const handleChangeId = () => {
    if (newId.trim() !== '') {
      node.emit('change_servo_id', [parseInt(id), parseInt(newId)]);
    }
  };
  
  const handleSetAlias = () => {
    if (aliasInput.trim() !== '') {
      node.emit('set_alias', [parseInt(id), aliasInput.trim()]);
      setAliasInput(''); // Clear input after sending
    }
  };
  
  const handleResetServo = () => {
    if (window.confirm('Are you sure you want to reset this servo to factory defaults? This will remove all calibration settings and aliases.')) {
      node.emit('reset_servo', [parseInt(id)]);
    }
  };
  
  const servoStatus = servo ? {
    Position: servo.position || 'N/A',
    Speed: servo.speed || 'N/A',
    Alias: servo.alias || 'None'
  } : {};
  
  if (!servo) {
    return (
      <div className="servo-debug">
        <article className="responsive">
          <header className="m-bottom-2">
            <h5>Loading Servo {id}...</h5>
          </header>
        </article>
      </div>
    );
  }
  
  return (
    <div className="servo-debug">
      <article className="responsive">
        {/* Header Section with Breadcrumb */}
        <header className="m-bottom-2">
          <nav aria-label="breadcrumb">
            <Link to="/" className="small">Home</Link>
            <span className="small">/</span>
            <span className="small" aria-current="page">Servo {id}</span>
          </nav>
          <h5 className="m-top-1">Servo Control Panel</h5>
          <p className="small text-gray">Configure and monitor servo behavior</p>
        </header>

        <div className="grid gap-2">
          {/* Left Column: Position Control */}
          <div className="s12 m6 l4">
            <section className="card p-3">
              <h6 className="m-bottom-2">Position Control</h6>
              <div className="center-align" role="group" aria-label="Position control">
                <div className="circular-slider-container">
                  <CircularSlider
                    width={180}
                    min={min}
                    max={max}
                    initialValue={position}
                    direction={-1}
                    knobPosition="right"
                    appendToValue="°"
                    valueFontSize="2.5rem"
                    trackColor="rgba(55, 71, 79, 0.3)"
                    progressColorFrom="var(--primary)"
                    progressColorTo="var(--primary)"
                    progressSize={12}
                    trackSize={12}
                    labelColor="var(--primary)"
                    knobColor="var(--primary)"
                    label=""
                    onChange={handlePositionChange}
                  />
                </div>
                <div className="field label border round m-top-2">
                  <label className="slider">
                    <input 
                      type="range" 
                      min="100" 
                      max="2000" 
                      step="1" 
                      value={speed}
                      onChange={handleSpeedChange}
                      aria-label="Servo speed control"
                    />
                    <span className="small">Speed: {speed}</span>
                  </label>
                </div>
              </div>
            </section>
          </div>

          {/* Middle Column: Status and Calibration */}
          <div className="s12 m6 l4">
            <section className="card p-3 m-bottom-2">
              <h6 className="m-bottom-2">Current Status</h6>
              <div className="status-grid">
                {Object.entries(servoStatus).map(([key, value]) => (
                  <div key={key} className="status-item p-1">
                    <span className="label text-gray">{key}</span>
                    <span className="value">{value}</span>
                  </div>
                ))}
              </div>
            </section>

            {servo.min_pos !== undefined && (
              <section className="card p-3">
                <h6 className="m-bottom-2">Calibration Range</h6>
                <div className="status-grid">
                  <div className="status-item p-1">
                    <span className="label text-gray">Min Position</span>
                    <span className="value">{servo.min_pos || 'Not calibrated'}</span>
                  </div>
                  <div className="status-item p-1">
                    <span className="label text-gray">Max Position</span>
                    <span className="value">{servo.max_pos || 'Not calibrated'}</span>
                  </div>
                </div>
              </section>
            )}
          </div>

          {/* Right Column: Controls */}
          <div className="s12 m12 l4">
            <section className="card p-3">
              <h6 className="m-bottom-2">Servo Configuration</h6>
              
              <div className="field label round m-bottom-2" style={{ display: 'flex' }}>
                <input 
                  className="border"
                  type="number" 
                  value={newId}
                  onChange={(e) => setNewId(e.target.value)}
                  aria-label="New servo ID"
                  min="1"
                  max="253"
                />
                <label>New Servo ID</label>
                <button 
                  onClick={handleChangeId}
                  disabled={!newId}
                  aria-label="Change servo ID"
                >
                  Change ID
                </button>
              </div>

              <div className="field label round m-bottom-2" style={{ display: 'flex' }}>
                <input 
                  className="border"
                  type="text" 
                  value={aliasInput}
                  onChange={(e) => setAliasInput(e.target.value)}
                  aria-label="Servo alias"
                  placeholder="Enter alias"
                />
                <label>Servo Alias</label>
                <button 
                  onClick={handleSetAlias}
                  disabled={!aliasInput}
                  aria-label="Set alias"
                >
                  Set Alias
                </button>
              </div>

              <div className="actions m-top-2">
                <button 
                  className="border m-right-2 p-2"
                  onClick={handleWiggle}
                  aria-label="Test servo movement"
                >
                  <i className="fa-solid fa-arrows-left-right m-right-1"></i>
                  Test Movement
                </button>
                <button 
                  className="border p-2"
                  onClick={handleCalibrate}
                  aria-label="Calibrate servo range"
                >
                  <i className="fa-solid fa-ruler m-right-1"></i>
                  Calibrate Range
                </button>
              </div>
              
              <div className="divider m-top-3 m-bottom-3"></div>
              
              <button 
                className="border error p-2 full-width"
                onClick={handleResetServo}
                aria-label="Reset servo to factory defaults"
              >
                <i className="fa-solid fa-rotate-left m-right-1"></i>
                Reset to Factory Defaults
              </button>
            </section>
          </div>
        </div>
      </article>
    </div>
  );
};

export default ServoDebug;
